/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:window1:824501:
  appc.background(230);
} //_CODE_:window1:824501:

public void StartSim(GButton source, GEvent event) { //_CODE_:startButton:848603:
  loop();
} //_CODE_:startButton:848603:

public void PauseSim(GButton source, GEvent event) { //_CODE_:pauseButton:450187:
  pause = !pause; 
  if (pause == true){
    loop();
  }
  else {
    noLoop();
    pauseButton.setText("Unpause");
  }
} //_CODE_:pauseButton:450187:

public void textfield1_change1(GTextField source, GEvent event) { //_CODE_:textfield1:716776:
  
} //_CODE_:textfield1:716776:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  window1 = GWindow.getWindow(this, "Window title", 0, 0, 240, 250, JAVA2D);
  window1.noLoop();
  window1.setActionOnClose(G4P.KEEP_OPEN);
  window1.addDrawHandler(this, "win_draw1");
  startButton = new GButton(window1, 80, 45, 80, 30);
  startButton.setText("Start");
  startButton.addEventHandler(this, "StartSim");
  pauseButton = new GButton(window1, 81, 92, 80, 30);
  pauseButton.setText("Pause");
  pauseButton.addEventHandler(this, "PauseSim");
  textfield1 = new GTextField(window1, 46, 161, 120, 30, G4P.SCROLLBARS_NONE);
  textfield1.setText("Enter Array Here: ");
  textfield1.setOpaque(true);
  textfield1.addEventHandler(this, "textfield1_change1");
  window1.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow window1;
GButton startButton; 
GButton pauseButton; 
GTextField textfield1; 
